In [46]:
LIST1=[[1,1,True],[2,3,False]]

In [146]:
import numpy as np

In [48]:
lt=np.array(LIST1)

In [49]:
type(lt[0][0])

numpy.int32

In [50]:
lt


array([[1, 1, 1],
       [2, 3, 0]])

In [43]:
lt.dtype

dtype('<U11')

In [37]:
lt.shape

(2, 3)

In [38]:
type(lt)

numpy.ndarray

In [19]:
list2=[1,'a']

In [20]:
lt2=np.array(list2)

In [11]:
lt2.dtype

dtype('<U11')

In [28]:
lt[0]

[1, 'a', True, 3]

In [29]:
lt[1]

['c', 'b', False]

In [36]:
lt.ndim

2

In [54]:
print(lt[1][0])

2


In [55]:
list2.append('c')

In [56]:
list2

[1, 'a', 'c']

In [60]:
list2.insert(0,'c')

In [61]:
list2

['c', 1, 'a', 'c']

In [62]:
list2.pop()

'c'

In [63]:
list2

['c', 1, 'a']

In [64]:
list2.reverse()

In [66]:
list2

['a', 1, 'c']

In [89]:
list=np.array(list2)

In [90]:
list

array(['a', '1', 'c'], dtype='<U1')

In [91]:
list.shape

(3,)

In [92]:
list[0]=2

In [93]:
list[2]=3

In [94]:
list

array(['2', '1', '3'], dtype='<U1')

In [95]:
list.dtype

dtype('<U1')

In [96]:
list.astype(int)

array([2, 1, 3])

In [97]:
list.dtype

dtype('<U1')

In [98]:
np.mean(list3)

9.0

In [104]:
list3=[[1,23,3],[1,2,3]]

In [106]:
list4=np.array(list3)

In [108]:
list4.dtype

dtype('int32')

In [100]:
np.append(list,list3)

array(['2', '1', '3', '1', '23', '3'], dtype='<U11')

In [101]:
np.delete(list,[1])

array(['2', '3'], dtype='<U1')

In [110]:
np.corrcoef(list4[0],list4[1])

array([[1.        , 0.08219949],
       [0.08219949, 1.        ]])

In [111]:
list

array(['2', '1', '3'], dtype='<U1')

In [112]:
list=list.astype(int)

In [113]:
list.dtype

dtype('int32')

In [114]:
list

array([2, 1, 3])

In [115]:
np.mean(list)

2.0

In [117]:
np.median(list)

2.0

In [123]:
dict={"name":'nishant',"age":38,"title":'manager'}

In [124]:
dict

{'name': 'nishant', 'age': 38, 'title': 'manager'}

In [125]:
dict['name']

'nishant'

In [126]:
dict['age']

38

In [129]:
dict={"child1": {"name":"x","age":5},"child2": {"name":"y","age":15}}

In [130]:
dict

{'child1': {'name': 'x', 'age': 5}, 'child2': {'name': 'y', 'age': 15}}

In [131]:
dict["child2"]

{'name': 'y', 'age': 15}

In [132]:
dict["child2"]["name"]

'y'

In [133]:
list4

array([[ 1, 23,  3],
       [ 1,  2,  3]])

In [134]:
list5=list4.reshape(3,2)

In [135]:
list5

array([[ 1, 23],
       [ 3,  1],
       [ 2,  3]])

In [150]:
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))


[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [161]:
x=np.array([[1,2,3],[3,4,5]])
y=np.array([[1,2,3],[3,4,5]])
print(x+y)
print(x-y)
print(x/y)
print(x%y)

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [171]:
np.ravel(x)

array([1, 2, 3, 3, 4, 5])